spring:
#  profiles:
#    active: web, prod
  datasource:
    url: jdbc:postgresql://localhost:5432/seminar_second
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate